---
name: Test Stress
author: Dan Mateas <dan@green-coding.berlin>
description: test

services:
  ubuntu-stress:
    type: container
    image: gcb_stress
    build:
      context: .
      dockerfile: Dockerfile

flow:
  - name: Stress
    container: ubuntu-stress
    commands:
      - type: console
        command: stress-ng -c 1 -t 1 -q
        note: Starting Stressa
